version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecg_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      # Hardcoded 'postgres' aqui para evitar erros de variável se o .env não carregar antes do YAML
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  app:
    build: .
    container_name: ecg_upload_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Monta o diretório atual (.) para /app dentro do container
      - .:/app
      
      # --- CORREÇÃO DE CAMINHO DA CHAVE ---
      # Opção A: Se a chave estiver dentro do projeto na pasta 'keys' (Recomendado)
      - ./keys/id_rsa_api:/app/keys/id_rsa_api:ro
      
      # Opção B: Se quiser usar o caminho absoluto do servidor (cuidado com permissões)
      # - /home/ecg-upload-service/.ssh/id_rsa_api:/app/keys/id_rsa:ro
      
    # --- CORREÇÃO DO COMANDO ---
    # Mudamos de 'main:app' para 'app.main:app' pois seu código está na pasta app/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: